#!/bin/bash

cd $OPENSHIFT_DATA_DIR
if [ ! -d apache-maven-3.3.3 ]; then
  wget http://www.eu.apache.org/dist/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
  tar -zxf apache-maven-3.3.3-bin.tar.gz
fi
 
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export MAVEN_HOME=$OPENSHIFT_DATA_DIR/apache-maven-3.3.3
export PATH=${JAVA_HOME}/bin:${PATH}

cd $OPENSHIFT_REPO_DIR

$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin/mvn -v

$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin/mvn -s $OPENSHIFT_REPO_DIR/.openshift/settings.xml -q clean package

